language: c

cache:
    - ccache
    - pip

compiler:
    - gcc

env:
    - VALAC=valac-0.16
    - VALAC=valac-0.24
    - VALAC=valac-0.26
    - VALAC=valac-0.28
    - VALAC=valac-0.30

before_install:
    - sudo add-apt-repository --yes ppa:vala-team
    - sudo apt-get update --quiet
    - sudo apt-get install --yes --force-yes $VALAC libglib2.0-bin
      libglib2.0-dev libsoup2.4-dev libfcgi-dev python-pip valadoc
    - sudo pip install cpp-coveralls sphinx PyYAML

before_script:
    - ./waf configure --enable-gcov VALAC=$VALAC
    - ./waf build

script:
    - ./build/tests/tests
      #    - valadoc --pkg=glib-2.0 --pkg=gio-2.0 --pkg=gio-unix-2.0 --pkg=libsoup-2.4
      #      --pkg=fcgi --target-glib=2.32 --directory=build/apidocs
      #      --vapidir=/usr/share/vala-0.26/vapi --vapidir=src/vsgi-fastcgi
      #      src/**/*.vala

after_success:
    - coveralls --repo-token $COVERALLS_TOKEN --build-root build
                --exclude build/examples --exclude build/tests
