language: c

cache:
    - ccache
    - pip

compiler:
    - gcc

before_install:
    - sudo add-apt-repository --yes ppa:vala-team
    - sudo apt-get update --quiet
    - sudo apt-get install --yes --force-yes valac libglib2.0-bin libglib2.0-dev
      libsoup2.4-dev libfcgi-dev python-pip valadoc
    - sudo pip install cpp-coveralls sphinx PyYAML

before_script:
    - ./waf configure CFLAGS='-fprofile-arcs -ftest-coverage' VALAFLAGS='--debug'
    - ./waf build

script:
    - ./build/tests/tests
    - valadoc --target=glib-2.32 --directory=$(mktemp -d) src/**/*.vala

after_success:
    - coveralls --repo-token $COVERALLS_TOKEN --build-root build
                --exclude build/examples --exclude build/tests
