#!/usr/bin/env python

def configure(cfg):
    pass

def build(bld):
    bld.shlib(
        target       = 'app',
        source       = 'app.vala',
        use          = 'valum',
        vapi_dirs    = '../../vapi',
        install_path = None)

